### ISSUE TITLE
Problem with Graphical User Interface 

### ISSUE THREAD

**Issue by litali** [MetaSys-LISBP/IsoCor#23]
Hello IsoCor team

I was unable to open the Graphical User Interface after installing anaconda and following the installation instruction.

after entering the commend **python.exe -m isocor**

I got 

(base) C:\windows\system32>python.exe -m isocor
Traceback (most recent call last):
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\isocor\__init__.py", line 10, in <module>
    from isocor.mscorrectors import MetaboliteCorrectorFactory
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\isocor\mscorrectors.py", line 15, in <module>
    from scipy.optimize import fmin_l_bfgs_b
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\optimize\__init__.py", line 400, in <module>
    from .optimize import *
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\optimize\optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\optimize\_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "C:\Users\litala.WISMAIN\Anaconda33\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.

Thank you :)

**Comment by pierremillard** [comment]
Hello @litali ,

I think there is an issue with your scipy package. Please, could you try to update scipy (command: 'pip install --upgrade scipy') and let us know if it works?

If this does not solve your issue, could you give us some information on your system and versions (OS? Python? Scipy?) ?

Best,
Pierre

**Comment by litali** [comment]
Hello Piere,

Thank you so much for your quick and helpful response.

It works now:)

Have a great day.

Lital
