### ISSUE TITLE
isocor -- windows fail to open

### ISSUE THREAD

**Issue by hejinfjmu** [MetaSys-LISBP/IsoCor#35]
After install isocor, comand "isocor" can not start IsoCor, the error was as followed:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hejin\AppData\Local\Programs\Python\Python312\Lib\site-packages\isocor\__main__.py", line 1, in <module>
    import isocor.ui.isocorgui
  File "C:\Users\Hejin\AppData\Local\Programs\Python\Python312\Lib\site-packages\isocor\ui\isocorgui.py", line 6, in <module>
    from isocor.ui.isocordb import EnvComputing
  File "C:\Users\Hejin\AppData\Local\Programs\Python\Python312\Lib\site-packages\isocor\ui\isocordb.py", line 6, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'

**Comment by gmat** [comment]
I guest you use python 3.12 

> [distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12.

for a "quick fix", install and use a **python < 3.12**

**Comment by gmat** [comment]
If you know _pip_ command you could install **setuptools**
```
 pip install setuptools
```
I'll do a PR to put **setuptools** in the [requirements](https://github.com/MetaSys-LISBP/IsoCor/blob/master/requirements.txt)

**Comment by hejinfjmu** [comment]
> I guest you use python 3.12
> 
> > [distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12.
> 
> for a "quick fix", install and use a **python < 3.12**

yes, I used 3.12, and I changed conda to install python, it can work. Thank you.

**Comment by pierremillard** [comment]
bug solved in IsoCor v2.2.2
